// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
import AboutMe from '../components/about_me';
import {SectionWrapper, Section} from '../components/section'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="proj-hero-bg pt-1"> {/* pt-1 to prevent margin collapsing */}
      <SectionWrapper>
        <Section content={children} />
        <Section content={<AboutMe />} />
      </SectionWrapper>
    </div>
  )
}
